host: 0.0.0.0
source: src
safe: true
encoding: utf-8
incremental: true
strict_front_matter: true
livereload: true
title: Stichting Ruby NL
email: contact@rubynl.org
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://rubynl.org"
twitter_username: amsrb
github_username:  amsrb

sass:
  sass_dir: stylesheets/_sass

exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
